import io
import re
from typing import Tuple

def export_to_markdown(title: str, report_body: str) -> str:
    """Formats report as clean markdown."""
    md_content = f"# {title}\n\n"
    md_content += f"*Generated by ResearchGPT Multi-Agent Assistant*\n\n"
    md_content += "---\n\n"
    md_content += report_body
    return md_content

def export_to_pdf(title: str, report_body: str) -> bytes:
    """Generates a PDF byte stream from report title and body using ReportLab."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib import colors

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Title'],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#1E293B'),
            spaceAfter=10,
            alignment=0
        )
        
        h1_style = ParagraphStyle(
            'Heading1_Custom',
            parent=styles['Heading1'],
            fontSize=15,
            leading=18,
            textColor=colors.HexColor('#0F172A'),
            spaceBefore=14,
            spaceAfter=6
        )

        h2_style = ParagraphStyle(
            'Heading2_Custom',
            parent=styles['Heading2'],
            fontSize=12,
            leading=15,
            textColor=colors.HexColor('#2563EB'),
            spaceBefore=10,
            spaceAfter=4
        )

        body_style = ParagraphStyle(
            'Body_Custom',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#334155'),
            spaceAfter=8
        )

        story = []
        story.append(Paragraph(title, title_style))
        story.append(Paragraph("<font color='#64748B'><i>ResearchGPT Multi-Agent Autonomous Report</i></font>", body_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#CBD5E1'), spaceAfter=15))

        # Parse markdown lines into PDF elements
        lines = report_body.split('\n')
        for line in lines:
            line_str = line.strip()
            if not line_str:
                continue
            if line_str.startswith('# '):
                story.append(Paragraph(line_str[2:], h1_style))
            elif line_str.startswith('## '):
                story.append(Paragraph(line_str[3:], h1_style))
            elif line_str.startswith('### '):
                story.append(Paragraph(line_str[4:], h2_style))
            elif line_str.startswith('- ') or line_str.startswith('* '):
                bullet_text = f"• {line_str[2:]}"
                # Clean basic markdown bold tags for reportlab
                formatted_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', bullet_text)
                story.append(Paragraph(formatted_text, body_style))
            else:
                formatted_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line_str)
                story.append(Paragraph(formatted_text, body_style))

        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    except Exception as e:
        # Fallback simple text PDF or error representation
        buffer = io.BytesIO()
        text_content = f"{title}\n\nResearchGPT Multi-Agent Report\n\n{report_body}"
        buffer.write(text_content.encode('utf-8'))
        buffer.seek(0)
        return buffer.getvalue()
